name: Android CI - Build APK

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: "Custom App Name"
        required: false
        default: "Varnika Jewellers"
      icon_url:
        description: "Custom Icon URL"
        required: false
        default: ""

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Give permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.app_name }}-debug
          path: app/build/outputs/apk/debug/app-debug.apk
